#!/usr/bin/env bash
# Opens (or updates) a PR with whatever the language-docs generators changed.
# Called by .github/workflows/sync-language-docs.yml after the generators ran.
set -euo pipefail

if [ "${GITHUB_ACTIONS:-}" != "true" ]; then
  echo "This script pushes branches and opens PRs; run it from CI only." >&2
  exit 1
fi

BRANCH=bot/language-docs-sync

if git diff --quiet; then
  echo "Docs already match /v3/languages; nothing to do."
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -B "$BRANCH"
git commit -am "Sync language docs with /v3/languages"
git push --force origin "$BRANCH"

BODY="Automated update: the GET /v3/languages response changed. Generated by the sync-language-docs workflow. Review the diff and merge.

Do not push manual commits to this branch: the next scheduled sync force-pushes over it."
# Generator warnings (languages skipped or missing from a matrix) belong in
# front of the reviewer, not in the workflow log.
if [ -s "${WARNINGS_FILE:-}" ]; then
  BODY="$BODY

⚠️ Generator warnings:
\`\`\`
$(cat "$WARNINGS_FILE")
\`\`\`"
fi

if [ "$(gh pr list --head "$BRANCH" --state open --json number --jq length)" -gt 0 ]; then
  echo "PR already open; the branch push updated it."
  gh pr edit "$BRANCH" --body "$BODY"
else
  gh pr create \
    --base main \
    --head "$BRANCH" \
    --title "Sync language docs with /v3/languages" \
    --body "$BODY"
fi
